site_name: Akatosh

nav:
  - overview: index.md
  - Examples:
      - examples/index.md
      - Instant Event: examples/instant_event.md
      - Continuous Event: examples/continuous_event.md
      - Event Priority: examples/event_priority.md
      - Pause Event: examples/pause_event.md
      - Cancel Event: examples/cancel_event.md
      - Create Event within Event: examples/create_event_within_event.md
      - Event After Another Event: examples/event_wait_event.md
      - Resource: examples/resource.md
  #- API Reference


theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  name: "material"

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.sections
    - navigation.indexes
    - navigation.tracking
    - content.code.copy

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
