[project]
name = "Akatosh"
version = "2.0.1"
authors = [{ name = "Yifei Ren", email = "ryf0510@live.com" }]
description = "A simple implement for discrete events simulation."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/ulfaric/Akatosh"
"Bug Tracker" = "https://github.com/ulfaric/Akatosh/issues"

[tool.setuptools]
packages = ["Akatosh"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["test"]
